chore(dependencies) Update all to latest  (#776)
* chore(package): update react-dom to version 15.2.0

https://greenkeeper.io/

* chore(package): update rimraf to version 2.5.3

https://greenkeeper.io/

* chore(package): update mocha to version 2.5.3

https://greenkeeper.io/

* chore(package): update react to version 15.2.0

https://greenkeeper.io/

* chore(package): update reselect to version 2.5.3

https://greenkeeper.io/

* chore(package): update postcss-reporter to version 1.4.1

https://greenkeeper.io/

* chore(package): update eslint-plugin-import to version 1.10.2

https://greenkeeper.io/

* chore(package): update eslint to version 3.0.1

https://greenkeeper.io/

* chore(package): update redux-saga to version 0.11.0

https://greenkeeper.io/

* chore(package): update webpack-hot-middleware to version 2.12.1

https://greenkeeper.io/

* chore(package): update lint-staged to version 1.0.2

https://greenkeeper.io/

* chore(package): update karma to version 1.1.1

https://greenkeeper.io/

* chore(package): update karma-coverage to version 1.1.0

https://greenkeeper.io/

* chore(package): update stylelint to version 6.9.0

https://greenkeeper.io/

* chore(update deps): updated all latest using ncu -u; minor breakage and new browser console messages

* fix(app.js): Uncaught TypeError: openSansObserver.check is not a function localhost/:75; caused by changes in fontfaceobserver 2.0.1 - and earlier?

* chore(package): update eslint-plugin-jsx-a11y to version 2.0.0

https://greenkeeper.io/

* chore(dependencies): updated to latest deps (webpack 2.1.0-beta.19 breaks prod - reverted); tests, dev (generators), prod all pass

* chore(dependencies) Update all to latest (did not try webpack.beta-20)

Tested Dev, Dev tunnel, Production builds.
Node 5.8.0
npm 3.8.2
Mac OS 10.11.5